import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import MustdoItems from "../components/MustdoItems";
import { Item } from "../components/Interfaces";
import {useState} from "react";
import AddMustdo from "../components/AddMustdo";
import { v4 as uuidv4 } from 'uuid';
const Home: NextPage = () => {
  const data: Array<Item> = [
    {
      id: "1",
      title: "TASK 1",
      priority: 1,
      description: "",
      status: false,
    },
    {
      id: "2",
      title: "TASK 2",
      priority: 2,
      description: "",
      status: false,
    },
    {
      id: "3",
      title: "TASK 3",
      priority: 3,
      description: "",
      status: false,
    },
    {
      id: "4",
      title: "TASK 4",
      priority: 4,
      description: "",
      status: false,
    },
    {
      id: "5",
      title: "TASK 5",
      priority: 5,
      description: "",
      status: false,
    },
  ];


  const [items, setItems] = useState<Array<Item>>(data);


  const deleteItem = (id: string) => {
    setItems(items.filter((item:Item) => item.id !== id));
    console.log(id, items.filter((item:Item) => item.id !== id))
  }

  const completeItem = (id: string) => {
    setItems(items.map((item:Item) => {
      if (item.id === id) {
        item.status = !item.status;
      }
      return item;
    }
    ));
  }

  // add new item
  const addItem = (item: Item) => {
    setItems([...items, {...item, id: uuidv4()}]);
  }










  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        {/* create three columns with list of todo items */}
          <div className="flex flex-col justify-center items-center w-6/12">
            <h1 className="text-2xl font-bold mb-5">Todo</h1>
            <ul className="w-full ">
              {/* list of todo items */}
              <MustdoItems items={items} deleteItem={deleteItem}completeItem={completeItem} />
              <AddMustdo addItem={addItem} />
            </ul>
        </div>
        {/* end of three columns */}
      </div>
    </>
  );
};

export default Home;
